/**
 * Plug-A-Pro AI operating loop — pluggable OpenBrain sinks.
 *
 * A sink is the boundary between the loop and OpenBrain storage. Three are
 * provided:
 *
 *  - memory: in-process arrays. Used by tests and by callers that want to batch.
 *  - file:   appends NDJSON to the repo's openbrain/ store and renders one
 *            markdown brief per candidate (matching the existing markdown
 *            convention in openbrain/engineering/*).
 *  - null:   no-ops. The safe default when OpenBrain is not configured.
 *
 * Every sink method is allowed to throw; the writer wraps all sink calls so a
 * storage failure can never propagate into a customer/payment/job flow.
 */

import { promises as fs } from 'fs'
import path from 'path'
import type { ImprovementCandidate, ObservationRecord } from './types'

export interface AiLoopSink {
  writeObservation(record: ObservationRecord): Promise<void>
  writeCandidate(record: ImprovementCandidate): Promise<void>
  listCandidates(): Promise<ImprovementCandidate[]>
}

// ── memory sink ───────────────────────────────────────────────────────────────

export interface MemorySink extends AiLoopSink {
  observations: ObservationRecord[]
  candidates: ImprovementCandidate[]
}

export function createMemorySink(): MemorySink {
  const observations: ObservationRecord[] = []
  const candidates: ImprovementCandidate[] = []
  return {
    observations,
    candidates,
    async writeObservation(record) {
      observations.push(record)
    },
    async writeCandidate(record) {
      candidates.push(record)
    },
    async listCandidates() {
      return [...candidates]
    },
  }
}

// ── null sink ─────────────────────────────────────────────────────────────────

export function createNullSink(): AiLoopSink {
  return {
    async writeObservation() {},
    async writeCandidate() {},
    async listCandidates() {
      return []
    },
  }
}

// ── file sink ─────────────────────────────────────────────────────────────────

const OBSERVATIONS_DIR = 'observations'
const CANDIDATES_DIR = 'improvement-candidates'

function renderCandidateMarkdown(c: ImprovementCandidate): string {
  const refs = c.exampleRefs.length ? c.exampleRefs.map((r) => `- \`${r}\``).join('\n') : '- (none captured)'
  return [
    `# ${c.title}`,
    '',
    `> Generated by the Plug-A-Pro AI operating loop on ${c.createdAt}.`,
    `> **Status:** ${c.status} · **Risk:** ${c.riskLevel} · **Owner:** ${c.recommendedOwnerRole} · **Human review required:** ${c.humanReviewRequired ? 'YES' : 'no'}`,
    '',
    '## Problem',
    '',
    c.problemSummary,
    '',
    `**Affected flow:** ${c.affectedFlow}  `,
    `**Category:** ${c.category}  `,
    `**Evidence count:** ${c.evidenceCount}`,
    '',
    '## Safe example references',
    '',
    refs,
    '',
    '## Suspected cause',
    '',
    c.suspectedCause ?? '_Unknown — investigation required._',
    '',
    '## Suggested investigation',
    '',
    c.suggestedInvestigation,
    '',
    '## Draft Claude Code task instruction',
    '',
    '```',
    c.draftTaskInstruction,
    '```',
    '',
  ].join('\n')
}

export function createFileSink(baseDir: string): AiLoopSink {
  const obsDir = path.join(baseDir, OBSERVATIONS_DIR)
  const candDir = path.join(baseDir, CANDIDATES_DIR)

  async function appendNdjson(dir: string, file: string, record: unknown) {
    await fs.mkdir(dir, { recursive: true })
    await fs.appendFile(path.join(dir, file), JSON.stringify(record) + '\n', 'utf8')
  }

  return {
    async writeObservation(record) {
      await appendNdjson(obsDir, 'observations.ndjson', record)
    },
    async writeCandidate(record) {
      await appendNdjson(candDir, 'candidates.ndjson', record)
      await fs.mkdir(candDir, { recursive: true })
      await fs.writeFile(path.join(candDir, `${record.id}.md`), renderCandidateMarkdown(record), 'utf8')
    },
    async listCandidates() {
      const file = path.join(candDir, 'candidates.ndjson')
      let raw: string
      try {
        raw = await fs.readFile(file, 'utf8')
      } catch {
        return []
      }
      const out: ImprovementCandidate[] = []
      for (const line of raw.split('\n')) {
        const trimmed = line.trim()
        if (!trimmed) continue
        try {
          out.push(JSON.parse(trimmed) as ImprovementCandidate)
        } catch {
          // Skip a corrupt line rather than fail the whole listing.
        }
      }
      return out
    },
  }
}

/**
 * Resolve the default sink from the environment.
 *  - OPENBRAIN_AILOOP_SINK=null      ⇒ null sink (explicit opt-out)
 *  - OPENBRAIN_STORE_DIR=<abs path>  ⇒ file sink there
 *  - otherwise                        ⇒ file sink at <cwd>/../openbrain (repo store)
 *
 * The file sink fails safely: if the path is not writable (e.g. read-only
 * serverless FS) the writer swallows the error, so this is safe as a default.
 */
export function resolveDefaultSink(): AiLoopSink {
  if (process.env.OPENBRAIN_AILOOP_SINK === 'null') return createNullSink()
  const explicit = process.env.OPENBRAIN_STORE_DIR
  if (explicit && explicit.trim()) return createFileSink(explicit.trim())
  return createFileSink(path.resolve(process.cwd(), '..', 'openbrain'))
}
