ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "providerCurrentLat" DOUBLE PRECISION;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "providerCurrentLng" DOUBLE PRECISION;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "providerLocationSharedAt" TIMESTAMP(3);
