/** Standard reason codes for admin CRUD operations. */
export const REASON_CODES = {
  // Customer — block
  CUSTOMER_BLOCKED_FRAUD: 'CUSTOMER_BLOCKED_FRAUD',
  CUSTOMER_BLOCKED_ABUSE: 'CUSTOMER_BLOCKED_ABUSE',
  CUSTOMER_BLOCKED_POLICY: 'CUSTOMER_BLOCKED_POLICY',
  // Customer — suspend
  CUSTOMER_SUSPENDED_DISPUTE: 'CUSTOMER_SUSPENDED_DISPUTE',
  CUSTOMER_SUSPENDED_REVIEW: 'CUSTOMER_SUSPENDED_REVIEW',
  // Customer — archive
  CUSTOMER_ARCHIVED_INACTIVE: 'CUSTOMER_ARCHIVED_INACTIVE',
  CUSTOMER_ARCHIVED_GDPR: 'CUSTOMER_ARCHIVED_GDPR',

  // Provider — suspend
  PROVIDER_SUSPENDED_COMPLAINT: 'PROVIDER_SUSPENDED_COMPLAINT',
  PROVIDER_SUSPENDED_REVIEW: 'PROVIDER_SUSPENDED_REVIEW',
  PROVIDER_SUSPENDED_SAFETY: 'PROVIDER_SUSPENDED_SAFETY',
  // Provider — archive
  PROVIDER_ARCHIVED_INACTIVE: 'PROVIDER_ARCHIVED_INACTIVE',
  PROVIDER_ARCHIVED_CONTRACT: 'PROVIDER_ARCHIVED_CONTRACT',
  // Provider — strikes
  PROVIDER_STRIKE_LATE: 'PROVIDER_STRIKE_LATE',
  PROVIDER_STRIKE_COMPLAINT: 'PROVIDER_STRIKE_COMPLAINT',
  PROVIDER_STRIKE_NO_SHOW: 'PROVIDER_STRIKE_NO_SHOW',

  // General purpose
  ADMIN_CORRECTION: 'ADMIN_CORRECTION',
  POLICY_VIOLATION: 'POLICY_VIOLATION',
  USER_REQUEST: 'USER_REQUEST',
  SYSTEM_AUTOMATED: 'SYSTEM_AUTOMATED',
} as const

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES]
